version: '3.8'

services:
  db:
    image: postgres:15
    container_name: swiftcodes-db
    environment:
      POSTGRES_DB: swift_codes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20032003
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: swiftcodes-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 20032003
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
